apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: raghava-art
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: YOUR_DOCKERHUB_USERNAME/raghava-art-frontend:1.0.0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: 80 }
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 250m, memory: 256Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: raghava-art
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
