namespace: raghava-art
frontend:
  image: YOUR_DOCKERHUB_USERNAME/raghava-art-frontend
  tag: "1.0.0"
  replicas: 2
backend:
  image: YOUR_DOCKERHUB_USERNAME/raghava-art-backend
  tag: "1.0.0"
  replicas: 2
